- name: Update apt cache
  sudo: true
  apt:  update_cache=yes cache_valid_time={{ rbenv_apt_cache_expiration }}

- name: Install dependencies
  sudo: yes
  apt:  pkg=git state=present install_recommends=no
