---
- include:       dependencies.yml
  when:          rbenv_install_dependencies

- name:          Check current installation
  shell:         rbenv --version
  ignore_errors: true
  register:      rbenv_already_installed

- name:          Create root directory
  file:          path={{ rbenv_root }} state=directory
  register:      rbenv_root_created

- name:          Install
  git:           repo=https://github.com/sstephenson/rbenv.git
                 dest={{ rbenv_root }}
                 version={{ rbenv_version }}
                 update=yes
  when:          rbenv_already_installed|failed or
                 rbenv_root_created|changed or
                 rbenv_version == "master" or
                 rbenv_already_installed.stdout | replace("rbenv ", "") != rbenv_version
  register:      rbenv_installed

- name:          Add binary to $PATH
  sudo:          true
  file:          path=/usr/local/bin/rbenv
                 src={{ rbenv_root }}/bin/rbenv
                 state=link
  when:          rbenv_installed|changed

- name:          Add init script
  sudo:          true
  template:      src=init.sh.j2
                 dest=/etc/profile.d/rbenv.sh
